Milestone 3
gabrielcoder247/my-portfolio-1 pull request #4
Opened 2021-07-23 12:46 UTC by gabrielcoder247

### Milestone 3
In this milestone:
**I have added the following:**

- Desktop Html
- Desktop CSS(style)
- Media query to toggle between screen sizes
- images and parse of the original Figma prototype

2021-07-23 13:08 UTC, carlos-ssh requested changes
Hi @gabrielcoder247, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 13:08 UTC, carlos-ssh commented on style.css
- Kindly align items in small screen.
![Screen Shot 2021-07-23 at 08 05 17](https://user-images.githubusercontent.com/22258274/126785928-7a558ac1-7cb9-4fa7-9070-8ff7c7f335fe.png)

2021-07-23 14:39 UTC, bellom commented on style.css
@gabrielcoder247, we still need to work on the small screen alignment, and also, the hamburger seems not to appear on the small screen.

Screenshot from your app.

![image](https://user-images.githubusercontent.com/31897434/126797803-4cc5de22-441a-456d-ab91-41cc180fc810.png)

 
![image](https://user-images.githubusercontent.com/31897434/126798066-2191c26b-6b50-4f57-8aa2-0746041fb771.png)



![image](https://user-images.githubusercontent.com/31897434/126796700-b961b9bf-7f52-4d9d-b6ae-5ede9883c8f4.png)




**Compare to the** [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9):
![image](https://user-images.githubusercontent.com/31897434/126798260-e6d4693a-5a8c-4d4b-b917-acda99cbb3be.png)

2021-07-24 01:39 UTC, carlos-ssh approved these changes
Hi @gabrielcoder247, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 07:56 UTC, merged